Hometask 1
Alaska-666/smart-home-2020 pull request #1
Opened 2020-02-28 18:47 UTC by Alaska-666

2020-03-10 16:43 UTC, a-ivanov requested changes

2020-03-10 16:43 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +    private static SensorEvent getNextSensorEvent() throws NoSuchMethodException, IllegalAccessException, InvocationTargetException, InstantiationException {
Все ошибки в сигнатуру генерации нового события не должны быть видны пользователям http://bit.ly/2v2kMZw к тому же тут нарушен SRP, вынесите эту логику в отдельный класс.

2020-03-10 16:43 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +    private void handleEvents() throws InvocationTargetException, NoSuchMethodException, InstantiationException, IllegalAccessException {
Нарушение SRP http://bit.ly/3aD3KAp

2020-03-10 16:43 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        EventHandler handler = new EventHandler(homeConditionPersister.readHome());
Старайтесь выносить зависимости полями в отдельный класс, здесь это можно сделать с домом и обработчиком http://bit.ly/2TBH1Pg

2020-03-10 16:43 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/persister/HomeConditionPersister.java
> +    SmartHome readHome();
Persist обычно означает долгосрочное сохранение, выберите здесь другое название для класса.

2020-03-10 16:43 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/sensorEvent/SensorDoorOpenEvent.java
> +    public void handleEvent(SmartHome smartHome) {
http://bit.ly/3ay2Dlc делегируйте обработку событий отдельному классу

2020-03-10 16:43 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/objects/Location.java
> +public class Location<T> {
А почему нельзя просто работать с конкретными классами дверей /света?

2020-03-11 16:50 UTC, Alaska-666 commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +    private void handleEvents() throws InvocationTargetException, NoSuchMethodException, InstantiationException, IllegalAccessException {
какой тогда смысл у самого класса Application, если у него не останется никакого функционала?

2020-03-11 16:59 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +    private void handleEvents() throws InvocationTargetException, NoSuchMethodException, InstantiationException, IllegalAccessException {
Он содержит конфигурационный код http://bit.ly/2wKc3f5

2020-03-11 20:47 UTC, a-ivanov requested changes

2020-03-11 20:47 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/objects/SmartHome.java
> +    public Light findLightByID(Room room, String id) {
Нарушен OCP, нам придется добалять по новому методу поиска на новый тип объектов дома. Для 1го дз достаточно делать явную итерацию по объектам, как было в начале (дом выдает список объектов). Но не надо поиск добавлять в дом.

2020-03-11 20:47 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventhandler/EventDoorHandler.java
> +        if (room.getName().equals("hall")) {
нарушен SRP http://bit.ly/2VO81g0

2020-03-11 20:47 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/objects/SmartHome.java
> +    public Light findLightByID(Room room, String id) {
Итерацию можно длать внутри обработчика событий.

2020-03-13 06:51 UTC, a-ivanov requested changes

2020-03-13 06:51 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventhandler/EventDoorHandler.java
> +    public Room findRoomByDoor(String id) {
А почему public? Это публичное апи или внутренняя имплементация? http://bit.ly/3aTPNOi

2020-03-13 06:51 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/eventhandler/EventHallDoorHandler.java
> +    private static void sendCommand(SensorCommand command) {
Нарушение SRP, исправьте

2020-03-15 20:45 UTC, a-ivanov approved these changes

2020-03-15 20:45 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SensorCommandSender.java
> +    public static void sendCommand(SensorCommand command) {
На будущее - здесь нет пользы в использовании статических методов http://bit.ly/3aLBprl, лучше интерфейс + имплементация в классе, так легче заменять будет при необходимости.

2020-03-16 17:23 UTC, merged